<?php

// Turn off all error reporting
error_reporting(1);

define('__ROOT__', (dirname(__FILE__)));

$sitemap_of_sitemap = "";
$sitemap_of_sitemap .= '<?xml version="1.0" encoding="UTF-8" ?>';
$sitemap_of_sitemap .= '<?xml-stylesheet type="text/xsl" href="//bannedadsense.com/main-sitemap.xsl"?>';
$sitemap_of_sitemap .= '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
$sitemap_of_sitemap .= "<sitemap>
							<loc>http://bannedadsense.com/sitemap-0.xml</loc>
							<lastmod>2016 09 28 04:20:09pm</lastmod>
						</sitemap>";

$sitemap_end = "</urlset>";
$sitemap_start = "";
$sitemap_start .= '<?xml version="1.0" encoding="UTF-8" ?>';
$sitemap_start .= '<?xml-stylesheet type="text/xsl" href="//bannedadsense.com/main-sitemap.xsl"?>';
$sitemap_start .= '<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';

include_once "dbConfig.php";

// Your SQL query go here. This query will display all record by setting the Limit.

$setLimit = 5000;
$sitemap_index = 1;

while(1) {
	
	$sitemap_content = "";
	$start_item = ($sitemap_index * $setLimit) - $setLimit;
	
	$sql = "SELECT * FROM domainlist LIMIT ".$start_item." , ".$setLimit;
	
	$query = mysqli_query($link,$sql);
	$count = $query->num_rows;
	
	if($count) {
		
		$sitemap_content .= $sitemap_start;
		
		while ($rec = mysqli_fetch_array($query,MYSQLI_ASSOC)) {
			$sitemap_content .= "
			<url>
				<loc>http://bannedadsense.com/".$rec["domain"].".html</loc>
				<changefreq>never</changefreq>
				<priority>0.8</priority>
			</url>";
		}
		
		$sitemap_content .= $sitemap_end;
		$filename = "sitemap-".$sitemap_index.".xml";
		$sitemap_xml_file = fopen(__ROOT__."/".$filename, "w") or die("Unable to open  file ".__ROOT__."/".$filename);
		fwrite($sitemap_xml_file, $sitemap_content);
		fclose($sitemap_xml_file);
		
		$sitemap_of_sitemap .= "
			<sitemap>
				<loc>http://bannedadsense.com/".$filename."</loc>
				<lastmod>".date("Y m d h:i:sa")."</lastmod>
			</sitemap>";
	
		
		
	}else{
		$sitemap_of_sitemap .= "</sitemapindex>";
		$sitemap_of_sitemap .= "<!-- XML Sitemap generated by Yoast SEO -->";
		$filename = "sitemap-index.xml";
		$sitemap_index_file = fopen(__ROOT__."/".$filename, "w") or die("Unable to open  file ".__ROOT__."/".$filename);
		fwrite($sitemap_index_file, $sitemap_of_sitemap);
		fclose($sitemap_index_file);
		break;
	}
	
	$sitemap_index++;
	
}
?>


<!-- XML Sitemap generated by bannedadsense.com SEO -->